name: Build latest (Android)

on: [push]

concurrency:
  group: ${{ github.ref }}-android
  cancel-in-progress: true

jobs:
  build-android:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew build


    - uses: ./.github/actions/notify_failure
      if: ${{ always() && steps.compile.outcome == 'failure' }}
      with:
        NOTIFY_MESSAGE: 'Failed to compile Haiku build'
        WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'

    - uses: ./.github/actions/upload_build
      if: ${{ always() && steps.compile.outcome  == 'success' }}
      with:
        SOURCE_FILE: 'android/app/build/outputs/apk/release//ClassiCube-android.apk'
        DEST_NAME: 'ClassiCube-android.apk'
